name: KeinShin

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "lightningsupport"

          replace: "lightning_support_group"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Things'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Kei

          commit_user_email: poxsisofficial@gmail.com
